import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LeftSide from "./LeftSide";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dua's and Ruqyah",
  description: "Generated by create by Md. Nazmus Sakib",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-3`}
      >
       <div className="grid grid-cols-12 gap-4">
        {/* left */}
        <div className="col-span-1 mx-auto h-screen">
          <LeftSide></LeftSide>
        </div>
         {/*middle  */}
         <div className="col-span-8 border border-red-700 h-screen">
        {children}
        </div>
        {/* right */}
        <div className="col-span-3 border border-red-700 h-screen">

        </div>
        </div>
      </body>
    </html>
  );
}
