import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import LeftSide from "@/components/LeftSide";
import RightSide from "@/components/RightSide";
import TopSide from "@/components/TopSide";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Dua's and Ruqyah",
  description: "Generated by create by Md. Nazmus Sakib",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${inter.variable} ${poppins.variable} antialiased m-3`}
      >
       <div className="grid grid-cols-12 gap-4">
        {/* left */}
        <div className="col-span-1 mx-auto h-screen">
          <LeftSide></LeftSide>
        </div>
         {/*middle  */}
         <div className="col-span-8 h-screen">
          {/* topSide */}
          <div>
            <TopSide></TopSide>
          </div>
        {children}
        </div>
        {/* right */}
        <div className="col-span-3 mx-auto h-screen">
        <RightSide></RightSide>
        </div>
        </div>
      </body>
    </html>
  );
}
